planner_node:
  ros__parameters:
    relevancy_map_topic: "/relevancy_map"
    frontier_topic: "/occ_map/frontiers"
    odom_topic: "/quadrotor/pose"
    region_size: 25.0
    global_replan_thres: 5.0
    local_replan_thres: 2.0
    global_relevancy_thres: 0.3
    retrieval_thres: 0.8
    ftr_relevancy_thres: 0.15

    # Deprecated
    # If sim is true, GPS waypoint not published
    sim: true
    # Now the planner is not differentiate GPS convention
    # It follows ROS convention and leave GPS conversion to TF handler
    
    # For robot initialization
    robot_initialization: false
    init_waypoints_x: 10.0
    init_waypoints_y: 10.0
    init_timeout: 10.0
    goal_x: [140.0, 163.0, 58.5]
    goal_y: [-243.0, -113.0, -205.5]
    goal_tol: [30.0, 30.0, 30.0]
    enable_goal: false
    log_path: " "